# Generated by Django 6.0.5 on 2026-05-27 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📄', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(default='#44b78b', max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_type', models.CharField(choices=[('theory', 'Theory'), ('code', 'Code'), ('commands', 'Commands')], max_length=20)),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learn.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cmd', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='learn.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
